#!/bin/bash
set -euo pipefail

VERSION="$(jq -r .version src/manifest.json)"
XPI="zotcard-${VERSION}.xpi"

rm -rf build
mkdir build

cd src
zip -r "../build/${XPI}" *
cd ../build

jq --arg hash "sha256:$(shasum -a 256 "${XPI}" | cut -d' ' -f1)" \
  '.addons["zotcard@zotero.org"].updates[0].update_hash = $hash' \
  ../updates.json.tmpl > ../updates.json
